import { Banner } from '@/components/Banner'
import { Header } from '@/components/Header'
import { Row } from '@/components/Row'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

const NotFoundPage = () => {
    return (
        <div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]'>
            <Head>
                <title>4 Frame - Not Found Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* Header */}
            <Header />
            <main className='relative pl-4 pb-24 lg:space-y-24 lg:pl-16'>
                {/* <Banner
                    netflixOriginals={netflixOriginals}
                    tvShows={tvShows}
                /> */}
                {/* Section */}
                <section className='md:space-y-10'>
                    {/* <Row title="Trending Now" movies={trendingNow} /> */}
                    {/* <Row title="Netflix Originals" movies={netflixOriginals} /> */}
                    {/* <Row title="Top Rated" movies={topRated} /> */}
                    {/* <Row title="Action Thrillers" movies={actionMovies} /> */}
                    {/* {list.length > 0 && <Row title="My List" movies={list} />} */}
                    {/* <Row title="Comedies" movies={comedyMovies} /> */}
                    {/* <Row title="Scary Movies" movies={horrorMovies} /> */}
                    {/* <Row title="Romance Movies" movies={romanceMovies} /> */}
                    {/* <Row title="Documentaries" movies={documentaries} /> */}
                </section>
                <div className='flex flex-col justify-center items-center gap-8'>
                    <h1 className='text-4xl'>ARE YOU LOST?</h1>
                    <p>its dangerous to go alone</p>
                    <Image
                        src='https://media.tenor.com/xSy4FAY4d1kAAAAd/link-zelda.gif'
                        alt='404'
                        width={650}
                        height={650}
                    />
                    <Link href='/' className='hover:text-slate-200 transition'>Go Back</Link>
                </div>
            </main>
            {/* Modal */}
        </div>
    )
}

export default NotFoundPage