
import { Banner } from '@/components/Banner'
import { Header } from '@/components/Header'
import Head from 'next/head'


export default function Home({ series }) {

  return (
    <div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]'>
      <Head>
        <title>4 Frame - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      <main>
        <Banner/>
        {/* Section */}
        <section>

        </section>
      </main>
      {/* Modal */}
    </div>
  )
}


