import { Layout } from '@/components/Layout'
import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>4 Frame</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout
        title="Home"
        description="This is the home page"
      >
        
      </Layout>
    </>
  )
}
