import { Banner } from '@/components/Banner'
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { Row } from '@/components/Row'
import Head from 'next/head'
import React from 'react'
import requests from '../../utils/requests'

const MoviesPage = ({ netflixOriginals, trendingNow, topRated, }) => {
    return (
        <div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]'>
            <Head>
                <title>4 Frame - Movies</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* Header */}
            <Header />
            <main className='relative pl-4 pb-24 lg:space-y-24 lg:pl-16'>
                <Banner netflixOriginals={trendingNow}/>
                {/* Section */}
                <section className='md:space-y-10'>
                    <Row title="Las más vistas" movies={netflixOriginals} />
                    <Row title="Mejor valoradas" movies={topRated} />
                    {/* <Row title="Trending Now" movies={trendingNow} /> */}
                    {/* <Row title="Action Thrillers" movies={actionMovies} /> */}
                    {/* <Row title="Comedies" movies={comedyMovies} /> */}
                    {/* <Row title="Scary Movies" movies={horrorMovies} /> */}
                    {/* <Row title="Romance Movies" movies={romanceMovies} /> */}
                    {/* <Row title="Documentaries" movies={documentaries} /> */}
                </section>
            </main>
            <Footer/>
        </div>
    )
}

export const getServerSideProps = async () => {

    const [
        netflixOriginals,
        trendingNow,
        topRated,
        actionMovies,
        comedyMovies,
        horrorMovies,
        romanceMovies,
        documentaries,

    ] = await Promise.all([
        fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
        fetch(requests.fetchTrending).then((res) => res.json()),
        fetch(requests.fetchTopRated).then((res) => res.json()),
        fetch(requests.fetchActionMovies).then((res) => res.json()),
        fetch(requests.fetchComedyMovies).then((res) => res.json()),
        fetch(requests.fetchHorrorMovies).then((res) => res.json()),
        fetch(requests.fetchRomanceMovies).then((res) => res.json()),
        fetch(requests.fetchDocumentaries).then((res) => res.json()),

    ])

    return {
        props: {
            netflixOriginals,
            trendingNow,
            topRated,
            actionMovies,
            comedyMovies,
            horrorMovies,
            romanceMovies,
            documentaries,
            // products,
        },
    }
}

export default MoviesPage